services:
  deliveries.api:
    container_name: deliveries
    networks:
      - gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development"
      - ServiceConfigurationDetails__ConsulUrl=http://consul:8500
      - ServiceConfigurationDetails__ApiUrl=http://deliveries.api:8080
      - ServiceConfigurationDetails__ApiServiceName=deliveriesapi
      - ServiceConfigurationDetails__ApiServiceId=v1
    ports:
      - "8001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro #this is very important for https
       
  orders.api:
    container_name: orders
    networks:
      - gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- Ocelot__Environment=ServiceDiscoveryDocker # Important, if this is not set then ocelot gateway will not be able to pick-up settings from the correct configuration file.
      - ServiceConfigurationDetails__ConsulUrl=http://consul:8500
      - ServiceConfigurationDetails__ApiUrl=http://orders.api:8080
      - ServiceConfigurationDetails__ApiServiceName=ordersapi
      - ServiceConfigurationDetails__ApiServiceId=v1
    ports:
      - "8002:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro #this is very important for https

  gateway.api:
    container_name: gateway_container
    networks:
      - gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=ServiceDiscoveryDocker
    ports:
      - "9001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro #this is very important for https

  consul:
    container_name: consul.container
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    networks: 
      - gateway
    ports:
      - "8500:8500"
       
networks:
  gateway:
    driver: bridge