services:
  deliveries.api:
    container_name: deliveries
    networks:
      - gateway
    env_file: 
      - secret.env
    ports:
      - "8000:8080"
      - "8001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro #this is very important for https
       
  orders.api:
    container_name: orders
    networks:
      - gateway
    env_file: 
      - secret.env
    ports:
      - "8050:8080"
      - "8051:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro #this is very important for https

  gateway.api:
    container_name: gateway
    networks:
      - gateway
    env_file: 
      - secret.env
    depends_on:
      - deliveries.api
      - orders.api 
    ports:
      - "9000:8080"
      - "9001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro #this is very important for https

networks:
  gateway: {} 

